name: "Softflowd"
version: "1.1.1"
slug: "softflowd"
description: "NetFlow exporter using softflowd with configurable timeouts and version"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
host_network: true
privileged:
  - NET_ADMIN
options:
  interface: any
  collector: 192.168.1.100:2055
  netflow_version: 9
  timeout_maxlife: 300        # 5 minutes
  timeout_tcp: 60             # 60s active TCP flow
  timeout_udp: 30             # 30s for UDP
  timeout_icmp: 30            # 30s for ICMP
  timeout_general: 60         # 60s for other protocols
  timeout_tcp_rst: 10         # 10s if TCP RST seen
  timeout_tcp_fin: 15         # 15s if TCP FIN seen
  timeout_expint: 10          # active export interval (softflowd-specific)
schema:
  interface: str
  collector: str
  netflow_version: int
  timeout_maxlife: int
  timeout_tcp: int
  timeout_udp: int
  timeout_icmp: int
  timeout_general: int
  timeout_tcp_rst: int
  timeout_tcp_fin: int
  timeout_expint: int
image: "ghcr.io/asucrews/softflowd-{arch}"
