name: Build Softflowd Add-on

on:
  push:
    branches: [main]
    paths:
      - 'addons/softflowd/**'
  workflow_dispatch:

env:
  ADDON_SLUG: softflowd
  GHCR_NAMESPACE: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, armv7, aarch64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push softflowd add-on
        uses: docker/build-push-action@v5
        with:
          context: ./addons/softflowd
          push: true
          platforms: linux/${{ matrix.arch }}
          tags: ${{ env.GHCR_NAMESPACE }}/${{ env.ADDON_SLUG }}-${{ matrix.arch }}:latest
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.arch }}-base:latest
