addonname: Build Softflowd Add-on (in series)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'addons/softflowd/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push for all architectures (in series)
        run: |
          for ARCH in amd64 aarch64 armv7; do
            echo "🔨 Building for $ARCH..."
            docker buildx build \
              --platform linux/$ARCH \
              --build-arg BUILD_FROM=ghcr.io/home-assistant/$ARCH-base:latest \
              --tag ghcr.io/${{ github.repository_owner }}/softflowd-$ARCH:latest \
              --push \
              ./addons/softflowd
          done
